create table retired_employees as select * from employees where 1=2;
select * from retired_employees;

declare 
    r_emp employees%rowtype;
begin
    SELECT * INTO R_EMP FROM EMPLOYEES WHERE employee_id=100;
    INSERT INTO retired_employees VALUES R_EMP;
END;
/
SET SERVEROUTPUT ON;

DECLARE 
    TYPE V_LIST IS VARRAY(5) OF VARCHAR2(20);
    EMPLOYEE V_LIST;
BEGIN 
    EMPLOYEE := V_LIST('MONU','SONU','NEERAJ','PRIYA','PANK');
    FOR  i IN 1..5 LOOP
     DBMS_OUTPUT.PUT_LINE(EMPLOYEE(i));
    END LOOP;
END;


DECLARE 
    TYPE V_LIST IS VARRAY(5) OF VARCHAR2(20);
    EMPLOYEE V_LIST;
BEGIN 
    EMPLOYEE := V_LIST('MONU','SONU','NEERAJ');
    FOR  i IN 1..EMPLOYEE.COUNT() LOOP
     DBMS_OUTPUT.PUT_LINE(EMPLOYEE(i));
    END LOOP;
END;
/
DECLARE 
    TYPE V_LIST IS VARRAY(5) OF VARCHAR2(20);
    EMPLOYEE V_LIST;
BEGIN 
    EMPLOYEE := V_LIST('MONU','SONU','NEERAJ');
    FOR  i IN EMPLOYEE.FIRST()..EMPLOYEE.LAST() LOOP
     DBMS_OUTPUT.PUT_LINE(EMPLOYEE(i));
    END LOOP;
END;



/

DECLARE 
    TYPE V_LIST IS VARRAY(50) OF VARCHAR2(20);
    EMPLOYEE V_LIST;
    --BOOLEAN X;
BEGIN 
 EMPLOYEE := V_LIST('AASHU','kUMAR','VERMA','AURANGABAD');
 DBMS_OUTPUT.PUT_LINE( EMPLOYEE.COUNT());
 DBMS_OUTPUT.PUT_LINE( EMPLOYEE.LIMIT());
 IF(EMPLOYEE.EXISTS(1)) THEN 
    DBMS_OUTPUT.PUT_LINE( 'TRUE');
 END IF;
 DBMS_OUTPUT.PUT_LINE('lAST '|| EMPLOYEE.LAST());
 DBMS_OUTPUT.PUT_LINE( EMPLOYEE.NEXT('NEXT '||2));
END;